"""add courses bookmarks and download logs

Revision ID: 898c8c503886
Revises: da64adb0484c
Create Date: 2026-05-10 02:18:07.983501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898c8c503886'
down_revision: Union[str, None] = 'da64adb0484c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_courses_owner_name')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uq_bookmarks_user_document')
    )
    op.create_index(op.f('ix_bookmarks_document_id'), 'bookmarks', ['document_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('course_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'document_id', name='uq_course_document')
    )
    op.create_index(op.f('ix_course_documents_course_id'), 'course_documents', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_documents_document_id'), 'course_documents', ['document_id'], unique=False)
    op.create_table('document_downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_downloads_document_id'), 'document_downloads', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_downloads_user_id'), 'document_downloads', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('teacher', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_column('documents', 'note')
    op.drop_column('documents', 'teacher')
    op.drop_column('documents', 'year')
    op.drop_index(op.f('ix_document_downloads_user_id'), table_name='document_downloads')
    op.drop_index(op.f('ix_document_downloads_document_id'), table_name='document_downloads')
    op.drop_table('document_downloads')
    op.drop_index(op.f('ix_course_documents_document_id'), table_name='course_documents')
    op.drop_index(op.f('ix_course_documents_course_id'), table_name='course_documents')
    op.drop_table('course_documents')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_document_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
