"""sync reports and reject reason

Revision ID: ced718bf594b
Revises: b7f9a2e0c4d1
Create Date: 2026-05-19 05:43:09.791841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ced718bf594b'
down_revision: Union[str, None] = 'b7f9a2e0c4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_reports_status'), table_name='document_reports')
    op.drop_constraint(op.f('document_reports_reviewed_by_fkey'), 'document_reports', type_='foreignkey')
    op.drop_column('document_reports', 'description')
    op.drop_column('document_reports', 'admin_note')
    op.drop_column('document_reports', 'reviewed_at')
    op.drop_column('document_reports', 'status')
    op.drop_column('document_reports', 'reviewed_by')
    op.execute("DROP TYPE IF EXISTS document_report_status_enum")
    op.add_column('documents', sa.Column('reject_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'reject_reason')
    op.execute(
        """
        DO $$
        BEGIN
            CREATE TYPE document_report_status_enum AS ENUM
                ('pending', 'reviewed', 'resolved', 'dismissed');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
        """
    )
    op.add_column('document_reports', sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document_reports', sa.Column('status', postgresql.ENUM('pending', 'reviewed', 'resolved', 'dismissed', name='document_report_status_enum'), server_default=sa.text("'pending'::document_report_status_enum"), autoincrement=False, nullable=False))
    op.add_column('document_reports', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_reports', sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document_reports', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_reports_reviewed_by_fkey'), 'document_reports', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_document_reports_status'), 'document_reports', ['status'], unique=False)
    # ### end Alembic commands ###
