"""add department and subject to documents

Revision ID: da64adb0484c
Revises: 9b600dddda87
Create Date: 2026-04-30 01:56:05.116968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da64adb0484c'
down_revision: Union[str, None] = '9b600dddda87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('subject', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'subject')
    op.drop_column('documents', 'department')
    # ### end Alembic commands ###
