services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWER}/backend:latest
    env_file:
      - /opt/uetdocs/.env.backend
    depends_on:
      - redis
    restart: always
    networks:
      - app_network

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWER}/frontend:latest
    depends_on:
      - backend
    restart: always
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/uetdocs/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  redis_data:
  certbot_www:

networks:
  app_network:
    driver: bridge
